### ISSUE TITLE
Are there duplicated packages for different notebooks?

### ISSUE THREAD

**Issue by Ben-FCC** [ContextLab/davos#114]
Hi there, 

I just finished reading this amazing package! 

I want to be clear about the duplicated packages before I start using it.
I mean, will Davos install the same package (e.g., numpy==1.23.1) twice for two different notebooks but both of them use numpy==1.23.1 if I don't set davos.project? 

If so, could you give more instructions about how to set davos.project? 

Please let me know if I misunderstood anything, thanks!

**Comment by paxtonfitzpatrick** [comment]
Hey @Ben-FCC, thanks for your question! 

By default, each notebook in which you `import davos` will create and use its own notebook-specifc project. A Davos "project" is essentially a directory that works similarly to a virtual environment and lives in `~/.davos/projects`. When you `smuggle` packages into a notebook, any packages (or specific versions of packages) that you don't already have installed in your "normal" Python environment will be installed into the notebook's project directory. That way, the packages you `smuggle` in one notebook won't interfere with the dependencies of another notebook, or the dependencies of other code that doesn't use Davos. 

So for example, say you created a new notebook named "**NotebookA**", and in it you ran:

```python
smuggle numpy as np    # pip: numpy==1.23.1
```

If you already had NumPy v1.23.1 installed in your Python environment, Davos would load it into the notebook just as if you had written `import numpy as np`. But if you didn't already have NumPy installed, or you had a version of NumPy other than v1.23.1 installed, Davos would install numpy==1.23.1 into **NotebookA**'s project directory and load it from there. Then any time you re-ran **NotebookA** in the future, NumPy v1.23.1 would be available in **NotebookA**'s project directory for that `smuggle` statement to load.

If you created a second notebook named "**NotebookB**" and ran the same `smuggle` statement there, Davos would do the same thing: is NumPy v1.23.1 already installed in your main Python environment? If yes, then simply import it. If no, then install numpy==1.23.1 into **NotebookB**'s project directory and import that.

So to answer your question: Davos won't install duplicate versions of packages you already have available in your main Python environment, but _will_ (by default) install any missing dependencies of different notebooks into different locations. So if you have multiple notebooks that happen to require installing the same NumPy version, Davos would install it into each of those notebooks' project directories. It's the same idea as if you created a separate virtual environment for each individual notebook. The default assumption is that different notebooks are unrelated to each other.

However, if you have multiple notebooks that _are_ related and therefore share the same set of dependencies (for example, different analyses for the same study), you can tell Davos to use the same project directory for each of those related notebooks by setting `davos.project` to the same value in each one. This would be like creating a single virtual environment that you ran all of your related notebooks inside. 

The value of `davos.project` determines the project used by the current notebook. The default project for each notebook is named after the notebook's absolute path in order to make it notebook-specific, but projects can be given any name you want (as long as it's a valid string). So the easiest way to share the same project across multiple notebooks is to choose a relevant name for your project and assign it to `davos.project` in each related notebook. 

For example, in **NotebookA**:

```python
davos.project = "my-project-name"
smuggle numpy as np    # pip: numpy==1.23.1
```

And then in **NotebookB**:

```python
davos.project = "my-project-name"
smuggle numpy as np    # pip: numpy==1.23.1
```

replacing `"my-project-name"` with whatever you want to name the shared project.  Now, **NotebookA** would create a project directory with that name (i.e., `~/.davos/projects/my-project-name`) and install numpy==1.23.1 into it (if necessary). Since **NotebookB** uses the same project as **NotebookA,** it would now be able to load NumPy v1.23.1 (or any other package installed by **NotebookA**) without needing to install its own separate copy. You could even remove the `# pip: numpy==1.23.1` comment from **NotebookB** if you knew for certain **NotebookA** would be run first (to make sure the right version of NumPy is available when **NotebookB** is run), but it's generally a good idea to specify the version in both notebooks so that they can be run in any order.

Hope this helps! If you're interested, [our paper on the Davos package](https://github.com/ContextLab/davos/blob/main/paper/main.pdf) includes a lot more information on creating and managing projects, including inspecting, renaming, deleting, and switching between them.

**Comment by Ben-FCC** [comment]
Hey @paxtonfitzpatrick,

This is really helpful! 
Thanks for your reply!
