### ISSUE TITLE
smuggle variable

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/davos#16]
What happens if someone wants to name a variable `smuggle`, as in `smuggle = 10`?  Do we raise an exception, like if you tried `import = 10`?

**Comment by jeremymanning** [comment]
This might break existing code... Probably ok though?

**Comment by paxtonfitzpatrick** [comment]
Currently, it would just overwrite the variable `smuggle` with 10, rather than the smuggle function: 
```python
In [1]:  smuggle numpy as np

In [2]:  smuggle = 10

In [3]:  smuggle pandas as pd
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-fc72f0750a8b> in <module>()
----> 1 smuggle(name="pandas", as_="pd")

TypeError: 'int' object is not callable
```

However, you can get `smuggle` functionality back any time you want it:

```python
In [4]:  print(smuggle)
10

In [5]:  davos.activate()

In [6]:  smuggle quail    # quail==0.2.0

In [7]:  print(smuggle)
<function smuggle_colab at 0x7f346966f440>
```

I actually didn't even know that trying to assign to `import` raises a SyntaxError -- I guess I've just never tried to do that... It wouldn't be too hard to make `smuggle` react the same way if we wanted to, and there's already an easy workaround for keeping it from breaking existing code -- currently, you can have:

```python
import davos

smuggle hypertools as hyp    # pip: -e git+https://github.com/ContextLab/hypertools.git@#egg=hypertools
from tqdm.notebook smuggle tqdm    # pip: -I tqdm==0.46.1 --target ~/foo/bar

davos.deactivate()
```
at the top of a notebook/script just to take care of smuggling any packages you need.  `davos.deactivate()` disables the parser from that point on, until you call `davos.activate()` again, like above.  The idea was to allow you to save whatever insignificant overhead the parser adds, in case you want to profile a function, heavily optimize something, etc.  But if we decided we want to make assigning a value to `smuggle` throw a SyntaxError like `import` does, the place in the code where we'd implement that anyway is what no longer runs after calling `davos.deactivate()`.  So that would allow you to add that^ block of code to the top of a script without breaking anything down below.

**Comment by jeremymanning** [comment]
Oh, perfect then.  I think defaulting to having smuggle overwritten is good for the sake of preserving existing code.  The import example is because normally you can't overwrite true keyword arguments in python.

**Comment by jeremymanning** [comment]
*built in keywords...not args

**Comment by jeremymanning** [comment]
I was worried that something about how we're getting smuggle to act like a keyword might mess with our ability to use it elsewhere

**Comment by paxtonfitzpatrick** [comment]
I tried to write the regex pattern for matching smuggle statements to handle most cases like that.  It'll ignore "smuggle" in a comment; inside parentheses (so it won't interfere with functions that have a "smuggle" keyword argument); inside normal quotes; in a multiline string (so it can be used in docstrings); as part of a variable name (`x = blah_blah_smuggle`)... 

But there isn't really a way to deal with assigning a value to it without throwing an error, which sounds like it's not something we want to do

**Comment by paxtonfitzpatrick** [comment]
I'm gonna go ahead and close this for now -- feel free to re-open if you think we should revisit this behavior at some point
