### ISSUE TITLE
installing from git

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/davos#22]
Do (or should) we support installing from github?  

If so, something like:

`smuggle hypertools as hyp #pip: git+https://github.com/ContextLab/hypertools.git==0.6.3`

should install the github version of hypertools (rather than the pipy version)

**Comment by paxtonfitzpatrick** [comment]
We do! `davos` supports (optionally, editable) installation from any of the [VCS options supported by `pip-install`](https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support).  From the README:
> You can also ensure the state of a packages matches a specific VCS branch, revision, ref, or release tag. For example:
> ```python
>      smuggle hypertools as hyp    # pip: git+https://github.com/ContextLab/hypertools.git@36c12fd
> ```
> will load [`hypertools`](https://hypertools.readthedocs.io/en/latest/) (aliased as "`hyp`"), as the package existed [on GitHub](https://github.com/ContextLab/hypertools), at commit [36c12fd](https://github.com/ContextLab/hypertools/tree/36c12fd). The general format for VCS references in [onion comments](https://github.com/ContextLab/davos#the-onion-comment) follows that of the [`pip-install`](https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support) command. See the [limitations section on smuggling from VCS](https://github.com/ContextLab/davos/blob/main/limitation-vcs-smuggle) for additional notes.

The general syntax (again, borrowed directly from pip's convention) is very close to what you wrote, with one tweak and a couple of additional options:
- An "`@`" symbol is used to specify the "state" of the smuggled project. This can be a branch name, commit hash, ref, release name, or other tag (it's also used in the syntax for installing from a [direct reference](https://www.python.org/dev/peps/pep-0440/#direct-references), which we support as well).  **Note**: GitHub release tags conventionally start with a **`v`** (see [`hypertools`](https://github.com/ContextLab/hypertools/tags), [`numpy`](https://github.com/numpy/numpy/tags), [`pandas`](https://github.com/pandas-dev/pandas/tags), [`brainiak`](https://github.com/brainiak/brainiak/tags)). So for your example, you'd do:

   ```python
   smuggle hypertools as hyp #pip: git+https://github.com/ContextLab/hypertools.git@v0.6.3
   ```
- the package name can be explicitly provided when installing from a VCS (or non-VCS) URL by appending `#egg=<pkg_name>`. If provided, pip uses this to identify the package and run various dependency checks before cloning the repository. **Note**: editable VCS URL-based installations _must_ provide the package name using the `#egg=` component; for non-editable installations, it is optional
- If you want to install a package that lives in a subdirectory of the main repository (i.e., the package's `setup.py` file is not in the repository root), you can specify the relative path to the package directory by appending `[#|&]subdirectory=path/to/pkg_dir`.  If the `#egg=` component is also used, `&` is used as the delimiter for the subdirectory component. Otherwise, `#` is used.  For example, to smuggle the final release version of the [`sherlock_helpers`](https://github.com/ContextLab/sherlock-topic-model-paper/tree/master/code/sherlock_helpers) package from the [sherlock-topic-model-paper](https://github.com/ContextLab/sherlock-topic-model-paper) repo, you would use:

   ```python
   smuggle sherlock_helpers    # pip: git+https://github.com/ContextLab/sherlock-topic-model-paper.git@v1.0#subdirectory=code/sherlock_helpers
   ```

**Comment by jeremymanning** [comment]
very cool!  i'll close this then...
