### ISSUE TITLE
`get_notebook_path` doesn't work when running with VSCode

### ISSUE THREAD

**Issue by le-big-mac** [ContextLab/davos#94]
I was attempting to run some Jupyter notebooks locally (testing Chatify for Neuromatch), and found that `davos` can't be imported if the notebooks are run in VSCode. The `get_notebook_path` function does not work with VSCode as the notebooks do not appear when running the command `jupyter notebook list`. 

The error is: `RuntimeError: Could not find notebook path for current kernel`.

I appreciate this is probably not a pressing concern, but might be good to note, particularly to Neuromatch students.

**Comment by jeremymanning** [comment]
thanks @le-big-mac --- we're on it!  we were able to replicate this issue in VS Code and we're working on a plan for handling it.

**Comment by paxtonfitzpatrick** [comment]
@le-big-mac thanks for the bug report! This has been fixed in #95. We have a few other fixes changes coming in the next release, so we're hoping to push that to PyPI by mid-next week. If you want to use Davos in VS Code in the mean time, you can install it directly from GitHub (`!pip install git+https://github.com/ContextLab/davos.git`).
